---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: local

verifier:
  name: terraform

suites:
  - name: default
    driver:
      root_module_directory: examples/hybrid_internal
      variable_files:
        - examples/hybrid_internal/terraform.tfvars
    verifier:
      systems:
        - name: default
          backend: local
          attrs:
            - test/integration/attributes/default/attrs.yml
