name: PR Open

on: [pull_request]

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.18.1'
          kubernetes version: 'v1.20.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: copy kube config to repo
        run: cp -r /home/runner/.kube .
      - name: write docker config
        run: |
          mkdir .docker
          cat << EOF > .docker/config.json
          ${{ secrets.DOCKER_CONFIG }}
          EOF
          cat << EOF > .kong_license
          ${{ secrets.KONG_LICENSE_FILE }}
          EOF
          ls -la
          cat .kube.config
          cp examples/hybrid/terraform.tfvars.examples examples/hybrid/terraform.tfvars
          sed -i 's-~/.kube/config-.kube/config-g' examples/hybrid/terraform.tfvars
          sed -i 's-~/.docker/config.json-.docker/config.json-g' examples/hybrid/terraform.tfvars
          sed -i 's-~/.kong_license-.kong_license-g' examples/hybrid/terraform.tfvars
      - name: wait
        run: while [[ $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: Kitchen Test
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test default --destroy=always
          aws-account-number: "REDECTED"
        env:
          TF_VAR_super_admin_password: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
          TF_VAR_kong_image: ${{ secrets.KONG_IMAGE }}
