name: PR Open

on: [pull_request]

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.18.1'
          kubernetes version: 'v1.20.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: write docker config
        run: |
          out=$(pwd)
          echo $out
          mkdir -p .ci/docker
          cp -r /home/runner/work/_temp/.minikube/ .ci/
          cp -r /home/runner/.kube .ci/
          sed -i 's-/home/runner/work/_temp-.ci-g' .ci/.kube/config
          cat << EOF > .ci/docker/config.json
          ${{ secrets.DOCKER_CONFIG }}
          EOF
          cat << EOF > .ci/kong_license
          ${{ secrets.KONG_LICENSE_FILE }}
          EOF
          cat .ci/.kube/config
          cp examples/hybrid_internal/terraform.tfvars.example examples/hybrid_internal/terraform.tfvars
          sed -i 's-~/.kube/config-.ci/.kube/config-g' examples/hybrid_internal/terraform.tfvars
          sed -i 's-~/.docker/config.json-.ci/docker/config.json-g' examples/hybrid_internal/terraform.tfvars
          sed -i 's-~/.kong_license-.ci/kong_license-g' examples/hybrid_internal/terraform.tfvars
      - name: wait
        run: while [[ $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: Kitchen Test
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test default --destroy=always
          aws-account-number: "REDECTED"
        env:
          TF_VAR_super_admin_password: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
          TF_VAR_kong_image: ${{ secrets.KONG_IMAGE }}
