name: PR Open

on: [pull_request]

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.18.1'
          kubernetes version: 'v1.20.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: wait
        run: while [[ $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: write config
        run: |
          gem install bundler --user
          bundle install
          mkdir -p .ci/docker
          cat << EOF > .ci/docker/config.json
          ${{ secrets.DOCKER_CONFIG }}
          EOF
          cat << EOF > .ci/kong_license
          ${{ secrets.KONG_LICENSE_FILE }}
          EOF
          cp examples/hybrid_internal/terraform.tfvars.example examples/hybrid_internal/terraform.tfvars
          sed -i 's-~/.docker/config.json-/github/workspace/.ci/docker/config.json-g' examples/hybrid_internal/terraform.tfvars
          sed -i 's-~/.kong_license-/github/workspace/.ci/kong_license-g' examples/hybrid_internal/terraform.tfvars
      - name: Kitchen Test
        run: kitchen test default --destroy=always
        env:
          TF_VAR_super_admin_password: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
          TF_VAR_kong_image: ${{ secrets.KONG_IMAGE }}
